name:                aoc2020
version:             0.1.0.0
license:             MIT

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -XOverloadedStrings
- -XExtendedDefaultRules

build-tools:
 - implicit-hie

library:
  source-dirs: src/haskell
  dependencies:
  - split
  - containers
  - text
  - attoparsec
  - regex-pcre-builtin

executables:
  aoc2020-exe:
    main:                Main.hs
    source-dirs:         src
    dependencies:
    - aoc2020

tests:
  aoc2020-test:
    main:                Spec.hs
    source-dirs:         tests/haskell
    dependencies:
    - aoc2020
    - HUnit
